[package]
name        = "httpdl"
version     = "0.3.0"
authors     = ["Igor Baidiuk <target.san@gmail.com>"]
description = "A simple HTTP file downloader. Supports specifying number of threads and limiting download speed"
edition     = "2021"

[dependencies]
clap            = "2.20.0"
thread-scoped   = "1.0.1"
hyper           = "0.10.0"
thiserror       = "1.0.31"
anyhow          = "1.0.58"

[dev-dependencies]
rand = "0.8.5"
