[package]
name = "httpdl"
version = "0.1.0"
authors = ["Igor Baidiuk <target.san@gmail.com>"]

[dependencies]
clap            = "*"
log             = "*"
simplelog       = "*"
thread-scoped   = "*"

[dependencies.hyper]
version = "*"
default-features = false
features = []
