[package]
name = "httpdl"
version = "0.2.0"
authors = ["Igor Baidiuk <target.san@gmail.com>"]

[dependencies]
docopt          = "0.7.0"
rustc-serialize = "0.3.22"
thread-scoped   = "1.0.1"
error-chain     = "0.7.2"

[dependencies.hyper]
version = "0.9.12"
default-features = false
features = []
