[package]
name = "httpdl"
version = "0.2.0"
authors = ["Igor Baidiuk <target.san@gmail.com>"]

[dependencies]
clap            = "2.18.0"
thread-scoped   = "1.0.1"
error-chain     = "0.7.2"

[dependencies.hyper]
version = "0.9.12"
default-features = false
features = []
