[package]
name        = "httpdl"
version     = "0.3.0"
authors     = ["Igor Baidiuk <target.san@gmail.com>"]
description = "A simple HTTP file downloader. Supports specifying number of threads and limiting download speed"

[dependencies]
clap            = "2.20.0"
thread-scoped   = "1.0.1"

[dependencies.hyper]
version = "0.9.12"
default-features = false
features = []

[dependencies.error-chain]
version = "0.7.2"
default-features = false
features = []
